### ISSUE TITLE
Rust edition 2021 is not supported

### ISSUE THREAD

**Issue by foxpy** [Relrin/cargo-test-all#1]
```
I/O error: Can't read Cargo.toml file. Reason: ErrorMessage { msg: "supported edition values are `2015` or `2018`, but `2021` is unknown" }

failed to parse the `edition` key

failed to parse manifest at `/path/to/Cargo.toml`
```

**Comment by Relrin** [comment]
Hello there and thank you for openning a PR! 

I looked into the issue and have updated the dependencies to support the Rust 2021 edition. Fixed it in the #3 PR. 
There might be some issues with running tests that require to use nightly toolchains, but rest should be fine
