### ISSUE TITLE
cargo-test-all tries to call cargo-clone and fails

### ISSUE THREAD

**Issue by foxpy** [Relrin/cargo-test-all#2]
Problem 1. README does not reflect that user has to install `cargo-clone`.

Problem 2. After installing `cargo-clone`, `cargo-test-all` still doesn't work:
```
Tests for the xxx crate are failing. Output:
error: Found argument '--prefix' which wasn't expected, or isn't valid in this context

USAGE:
    cargo clone [FLAGS] [OPTIONS] <dummy> <crate>... [-- <directory>]

For more information try --help
```

**Comment by Relrin** [comment]
The README have been updated, thank you for pointing out on the issue!

> error: Found argument '--prefix' which wasn't expected, or isn't valid in this context

This issue of this run command it's because such option has been dropped and replaced onto a new. But this thing was quite easy fixed by the changes in the #3 PR
